#bash run_anmm.sh
#bash run_drmm_tks.sh
bash run_duet.sh
bash run_matchpyramid.sh
bash run_mvlstm.sh
bash run_drmm.sh
bash run_dssm.sh
bash run_cdssm.sh
bash run_arci.sh
bash run_arcii.sh
bash run_cdssm_word.sh
bash run_conv_knrm.sh
bash run_knrm.sh
